### ISSUE TITLE
Stopped working on Win 10 / ST4 4152 after update from Diffy to Diffable

### ISSUE THREAD

**Issue by derikmacedo** [yaroslavyaroslav/Diffable#1]
Stopped working on Win 10 / ST4 4152 after update from Diffy to Diffable

**Comment by yaroslavyaroslav** [comment]
Hi, thanks for reaching out. But more context required here. How exactly is this issue appears? Is there no options reveals when two tabs/groups selected or is it keybinding become broken, or some other option?

<img width="661" alt="Screenshot 2023-10-16 at 15 54 30" src="https://github.com/yaroslavyaroslav/Diffable/assets/16612247/3eb65d2a-517b-4b11-8cb1-facfb42d4ac8">

**Comment by derikmacedo** [comment]
![image](https://github.com/yaroslavyaroslav/Diffable/assets/4296793/618cea06-acb6-48a2-b56c-9a8792f6402b)

![image](https://github.com/yaroslavyaroslav/Diffable/assets/4296793/ebf6f809-f98a-48cb-acb0-13fbc10d5094)

If I'm not mistaken, previously the characters were highlighted and not just the line.
And I don't see the shortcut keys either.

**Comment by yaroslavyaroslav** [comment]
Absolutely, I've got you covered. There have been several breaking changes introduced with this release

1. The command name has changed from `diffy` to `diffable`. Thus, you will need to manually adjust your keybindings. Please refer to [this chapter](https://github.com/yaroslavyaroslav/Diffable/blob/develop/messages/2.0.0.md#feature-list) and [this chapter](https://github.com/yaroslavyaroslav/Diffable/blob/develop/README.md#settings) for guidance.
2. The custom diff engine has been replaced with the built-in one from ST. While this introduces an additional keystroke for a char by char comparison, it's as simple as pressing `super+k, [THEN] super+/`. Doing so will produce the same result as shown in the below image.

FYI: I'd like to keep the Diffy plugin key-binding enabled in this one, but unfortunately it's causing some conflicts. The package control repo tests aren't passing satisfactorily this way as it appears that there are some conflicts with Sublime Text's own key bindings.

<img width="757" alt="Screenshot 2023-10-16 at 19 46 41" src="https://github.com/yaroslavyaroslav/Diffable/assets/16612247/d79387ce-fc80-43a0-b1c7-d38d1ec42fee">

**Comment by yaroslavyaroslav** [comment]
I believe this one is solved as well. Please reopen it if not.

**Comment by edditler** [comment]
Hi, I have a similar problem.
When I list the installed packages, I see Diffable v2.0.1.
I'm also on windows using Sublime Text 4152.

- Hitting Ctrl+Shift+P and typing "Diff" I don't see Diffable at all.
- If I right click into the text field I have a Diffable context menu, but all options are grayed out. 
- I also set a keybinding to ctrl+k, ctrl+d but that doesn't do anything either.

I'm doing all this with two tabs open side by side.

**Comment by yaroslavyaroslav** [comment]
@edditler aha, I see. Should be fixed in 2.0.2. 

FYI: you are talking not about active tabs (which is super+mouse1) but about ST windows groups which were broken 2.0.1.

**Comment by fruffy** [comment]
When will this version roll out? I installed the latest version from package control, but I am facing the same issue. Inline diff does not work anymore.

**Comment by yaroslavyaroslav** [comment]
It's already released. Could you provide st and plugin version and how do you try to use it, i.e. tabs or groups?

**Comment by yaroslavyaroslav** [comment]
> When will this version roll out? I installed the latest version from package control, but I am facing the same issue. Inline diff does not work anymore. 

It's already released. Could you provide st and plugin version and how do you try to use it, i.e. tabs or groups?

**Comment by fruffy** [comment]
> > When will this version roll out? I installed the latest version from package control, but I am facing the same issue. Inline diff does not work anymore.
> 
> It's already released. Could you provide st and plugin version and how do you try to use it, i.e. tabs or groups?

SublimeBuild 4152, package version is `2.0.2`. 
Trying to use a split view diff.  Two windows next to each other.

**Comment by yaroslavyaroslav** [comment]
> > > When will this version roll out? I installed the latest version from package control, but I am facing the same issue. Inline diff does not work anymore.
> 
> > 
> 
> > It's already released. Could you provide st and plugin version and how do you try to use it, i.e. tabs or groups?
> 
> 
> 
> SublimeBuild 4152, package version is `2.0.2`. 
> 
> Trying to use a split view diff.  Two windows next to each other. 

Let's dig deeper. How exactly the plugin is not working? Is it the context menu items are inactive or is it something else?

Elaboration of steps you're taking before it fails would really help.

**Comment by yaroslavyaroslav** [comment]
> Trying to use a split view diff.  Two **windows** next to each other. 

Wait a minute! Do I got you right that you mean literally windows? Not two tabs or groups of tabs in a row within a single ST window, but two separate windows exactly?

**Comment by fruffy** [comment]
> > Trying to use a split view diff.  Two **windows** next to each other.
> 
> Wait a minute! Do I got you right that you mean literally windows? Not two tabs or groups of tabs in a row within a single ST window, but two separate windows exactly?

Apologize for the confusion two columns (Alt+Shift+2).

I took a screenshot, but while taking the screenshot I realized that diffable works now!

However, unlike diffy, it does not seem to highlight text anymore but instead just marks the lines that have changed?

The command I used was `Diffable: Compare Inline`

![image](https://github.com/yaroslavyaroslav/Diffable/assets/5960321/e449cb70-dc26-4830-b05c-39ce7967f672)

**Comment by yaroslavyaroslav** [comment]
@fruffy yep that helped. 

As I said a few comments before:

> The custom diff engine has been replaced with the built-in one from ST. While this introduces an additional keystroke for a char by char comparison, it's as simple as pressing `super+k, [THEN] super+/`. Doing so will produce the same result as shown in the below image.

But I'll consider to eliminate this additional step in the future somehow. I see how confusing it is.

**Comment by fruffy** [comment]
Ah, I missed that one. Thanks! Everything work as intended it seems.

I have rebound these shortcuts, which explains why it didn't work. Maybe adding a specific command that includes this step helps?

**Comment by yaroslavyaroslav** [comment]
> I have rebound these shortcuts, which explains why it didn't work. Maybe adding a specific command that includes this step helps? 

Yep, there's a branch related to that `feature/auto-diffs-toggle`. But there's a hitch with it: the caret should be within the diff to get it toggled, and unfortunately I'm not aware about an easy yet user convenient way to do that properly. 

I mean `select_all` -> `toggle_diff` isn't a proper way to do that coz it's either messes with user caret obviously or making a plugin overcomplicated by storing an initial caret place within.

So it's kind of in WIP, but I wouldn't expect it anytime soon.
