### ISSUE TITLE
Can get this working with Kaleidoscope 2.4.5

### ISSUE THREAD

**Issue by hulleyrob** [yaroslavyaroslav/Diffable#5]
The inline menu option works but nothing happens when I choose Kaleidoscope. 

What setup is required to get this to work?

**Comment by yaroslavyaroslav** [comment]
I've tested it with Kaleidoscope 3.9 with `ksdiff` cli tool installed. Honestly I have no idea what Kaleidoscope 2.* actually was, but I believe it should work if command line tool for it were presented in that version.

**Comment by hulleyrob** [comment]
yeah it used ksdiff also. Was fine for my usage so didnt upgrade and still works on a new Mac.

Is there any setup needed that I could have missed as I just installed the Diffable the inline diff works and the Kaleidoscope menu item is there just doesnt seem to do anything.

**Comment by yaroslavyaroslav** [comment]
I believe not, if it's in the $PATH. To be honest the code to kick off kaleidoscope was provided by the team itself. So I actually never dig deep enough in it. 

Here's the line that it triggers on a keypress:

`ksdiff_path, "-l", "Sublime Text", lhs_path, rhs_path], pass_fds=[lhs_read_fd, rhs_read_fd], close_fds=True)` I think if it runs in plain bash on your side it should do so in ST as well. 

Ps: just a dummy reminder, there has to be exact two sheets/groups presented on a window to make things work.

**Comment by hulleyrob** [comment]
Weirdly ive had a look around and it works file with this package https://github.com/colinta/SublimeFileDiffs
 which is only using the following config
{
"cmd": ["ksdiff", "$file1", "$file2"]
}
no idea why I couldnt get it working with your package, maybe a conflict with another package????? (I didnt install these two at the same time)

yeah I worked out what you said as the menu never appears unless I selected two files. 

Anyway main thing is I can use KSDIFF now so unless you have any ideas from the above its fine to just leave it and thanks for your help.

**Comment by yaroslavyaroslav** [comment]
I would say those are slightly different commands, in case of this plugin it has -l attribute in addition to the latter one. 

But I'm really glad to hear that you were able to make it work in anyway.

**Comment by hulleyrob** [comment]
Closing as im using an unsupported version of Kaleidoscope and this package requires version >=3.

Thanks for assistance.
